name: "automated tests serverest"
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test-linux:
    name: API@${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Step 1 - Install operating system dependencies
        run:  |
          npm i -g rimraf
          npm install
          pwd
          ls
      - name: Step 3 - Run tests
        run: npm run test-prod

      - name: Step 4 - Publishing Allure artifact to GitHub Actions
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report

      - name: Step 5 - Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: report